/*
 * Copyright 2016 Azavea
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package geotrellis.vectortile.internal.vector_tile

private[vectortile] object VectorTileProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChF2ZWN0b3JfdGlsZS5wcm90bxILdmVjdG9yX3RpbGUi4wUKBFRpbGUSLwoGbGF5ZXJzGAMgAygLMhcudmVjdG9yX3RpbGUuV
  GlsZS5MYXllclIGbGF5ZXJzGvIBCgVWYWx1ZRIhCgxzdHJpbmdfdmFsdWUYASABKAlSC3N0cmluZ1ZhbHVlEh8KC2Zsb2F0X3Zhb
  HVlGAIgASgCUgpmbG9hdFZhbHVlEiEKDGRvdWJsZV92YWx1ZRgDIAEoAVILZG91YmxlVmFsdWUSGwoJaW50X3ZhbHVlGAQgASgDU
  ghpbnRWYWx1ZRIdCgp1aW50X3ZhbHVlGAUgASgEUgl1aW50VmFsdWUSHQoKc2ludF92YWx1ZRgGIAEoElIJc2ludFZhbHVlEh0KC
  mJvb2xfdmFsdWUYByABKAhSCWJvb2xWYWx1ZSoICAgQgICAgAIajQEKB0ZlYXR1cmUSEQoCaWQYASABKAQ6ATBSAmlkEhYKBHRhZ
  3MYAiADKA1CAhABUgR0YWdzEjcKBHR5cGUYAyABKA4yGi52ZWN0b3JfdGlsZS5UaWxlLkdlb21UeXBlOgdVTktOT1dOUgR0eXBlE
  h4KCGdlb21ldHJ5GAQgAygNQgIQAVIIZ2VvbWV0cnka3AEKBUxheWVyEhsKB3ZlcnNpb24YDyACKA06ATFSB3ZlcnNpb24SEgoEb
  mFtZRgBIAIoCVIEbmFtZRI1CghmZWF0dXJlcxgCIAMoCzIZLnZlY3Rvcl90aWxlLlRpbGUuRmVhdHVyZVIIZmVhdHVyZXMSEgoEa
  2V5cxgDIAMoCVIEa2V5cxIvCgZ2YWx1ZXMYBCADKAsyFy52ZWN0b3JfdGlsZS5UaWxlLlZhbHVlUgZ2YWx1ZXMSHAoGZXh0ZW50G
  AUgASgNOgQ0MDk2UgZleHRlbnQqCAgQEICAgIACIj8KCEdlb21UeXBlEgsKB1VOS05PV04QABIJCgVQT0lOVBABEg4KCkxJTkVTV
  FJJTkcQAhILCgdQT0xZR09OEAMqBQgQEIBAQgJIAw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}
