---

- name: Provison EC2 Cluster
  hosts: localhost
  gather_facts: False
  
  tasks:
    - name: EC2 VPC Group for cluster
      local_action:
        module: ec2_group
        region: "{{ region }}"
        name: "{{ cluster_name }}"
        description: "{{ cluster_name }} security group"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
          - proto: all
            cidr_ip: "{{ allow_vpn_from_subnet }}"
          - proto: all
            group_name: "{{ cluster_name }}"

        rules_egress:
          - proto: all
            cidr_ip: "0.0.0.0/0"
  
    - name: Launch master
      local_action: 
        module: ec2 
        image:          "{{ image }}" 
        instance_type:  "{{ instance_type }}"
        key_name:       "{{ ec2_key_name }}"
        group:          "{{ cluster_name }}"
        region:         "{{ region }}"
        instance_tags:  
          spark-role: "{{ cluster_name }}-master"
        count_tag:
          spark-role: "{{ cluster_name }}-master"
        exact_count:    1
        wait:           true
      register: master

    - name: Add master instance to host group
      add_host:
        hostname={{ item.public_ip }}
        groups=ec2_hosts,master
        ansible_ssh_user="ubuntu"
        ansible_ssh_private_key_file="{{ ec2_key_file }}"       
        instance_id={{ item.id }}
        public_ip={{ item.public_ip }}
        private_ip={{ item.private_ip }}
        private_dns_name={{ item.private_dns_name }}
      with_items: master.tagged_instances

    - name: Launch workers
      local_action:
        module: ec2
        image:          "{{ image }}"         
        instance_type:  "{{ instance_type }}" 
        key_name:       "{{ ec2_key_name }}" 
        group:          "{{ cluster_name }}"
        region:         "{{ region }}"
        instance_tags:  
          spark-role: "{{ cluster_name }}-worker"
        count_tag:      
          spark-role: "{{ cluster_name }}-worker"
        exact_count:    "{{ worker_count }}"
        wait:           true
      register: workers

    - name: Add worker instance to host group
      add_host:
        hostname={{ item.public_ip }} 
        ansible_ssh_user="ubuntu"
        ansible_ssh_private_key_file="{{ ec2_key_file }}"       
        groups=ec2_hosts,workers
        instance_id={{ item.id }}
        public_ip={{ item.public_ip }}
        private_ip={{ item.private_ip }}        
        private_dns_name={{ item.private_dns_name }}        
      with_items: workers.tagged_instances
 
    - name: Update EC2 Hosts Inventory
      local_action: template src=templates/cluster_inventory.j2 dest=./hosts
