---

- name: Master
  hosts: master
  roles:
    - common
    - hadoop
    - hadoop_namenode
    - spark
    - spark_master
  gather_facts: False

  tasks:
    - include_vars: group_vars/cluster.yml
  