---
#Note: this will only terminate a running cluster
# it will have no effect on stopped cluster
- name: Terminating Cluster
  hosts: localhost
  gather_facts: False
  
  tasks:
    - include_vars: group_vars/cluster.yml  

    - name: Stop Cluster
      local_action: 
        module: ec2 
        region: "{{ region }}" 
        instance_ids: "{{ cluster_instance_ids }}"
        state: 'absent'

