#!/bin/sh
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO
 
ACCUMULO_DIR=/usr/lib/accumulo
 
start() {
  $ACCUMULO_DIR/bin/start-here.sh
}
 
stop() {
  $ACCUMULO_DIR/bin/stop-here.sh
}

restart() {
  stop
  start
}
 
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac